Django/디버깅 시험대비/4-21 디버깅 시험대비/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('<int:user_pk>/update/', views.update, name='update'),
    path('<int:user_pk>/delete/', views.delete, name='delete'),
    path('<int:user_pk>/password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

Django/디버깅 시험대비/4-21 디버깅 시험대비/movies/urls.py
from django.urls import path
from .import views


app_name = "movies"

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:movies_pk>/', views.detail, name='detail'),
    path('<int:movies_pk>/update/', views.update, name='update'),
    path('<int:movies_pk>/delete/', views.delete, name='delete'),
    path('<int:movies_pk>/comment/', views.comment_create, name='comment_create'),
    path('<int:movies_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:movies_pk>/likes', views.likes, name='likes'),

]

Django/디버깅 시험대비/4-21 디버깅 시험대비/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

Django/디버깅 시험대비/4-21 디버깅 시험대비/movies/models.py
from django.db import models
from django.conf import settings
# Create your models here.


class Movie(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    like_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies')
    title = models.CharField(max_length = 10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    content = models.CharField(max_length=200)
    movie = models.ForeignKey(Movie, on_delete = models.CASCADE)

Django/디버깅 시험대비/4-21 디버깅 시험대비/movies/forms.py
from django import forms
from .models import Movie, Comment

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'content')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

Django/디버깅 시험대비/4-21 디버깅 시험대비/movies/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from .models import Movie, Comment
from .forms import MovieForm, CommentForm
# Create your views here.
@require_http_methods(['GET'])
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies' : movies,
    }
    return render(request, 'movies/index.html', context)

@require_http_methods(['GET', 'POST'])
@login_required
def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.user = request.user
            movie.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm()
    context = {
        'form' : form,
    }
    return render(request, 'movies/create.html', context)

@require_http_methods(['GET'])
def detail(request, movies_pk):
    movie = Movie.objects.get(pk = movies_pk)
    comments = movie.comment_set.all()
    comment_form = CommentForm()
    context = {
        'movie' : movie,
        'comments' : comments,
        'comment_form' : comment_form,
    }
    return render(request, 'movies/detail.html', context)

@require_http_methods(['GET', 'POST'])
@login_required
def update(request, movies_pk):
    movie = Movie.objects.get(pk = movies_pk)
    if request.user == movie.user:
        if request.method == 'POST':
            form = MovieForm(request.POST, instance=movie)
            if form.is_valid():
                form.save()
                return redirect('movies:detail', movie.pk)
        else:
            form = MovieForm(instance=movie)
        context = {
            'form' : form,
            'movie': movie,
        }
        return render(request, 'movies/update.html', context)
    return redirect("movies:detail", movie.pk)

@require_http_methods(['POST'])
@login_required
def delete(request, movies_pk):
    movie = Movie.objects.get(pk = movies_pk)
    if request.user == movie.user:
        movie.delete()
        return redirect('movies:index')
    return redirect('movies:detail', movie.pk)

@require_http_methods(['POST'])
@login_required
def comment_create(request, movies_pk):
    movie = Movie.objects.get(pk = movies_pk)
    comments = movie.comment_set.all()
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.movie = movie
        comment.user = request.user
        comment.save()
        return redirect('movies:detail', movie.pk)
    context = {
        'comment_form' : comment_form,
        'movie' : movie,
        'comments' : comments,
    }
    return render(request, 'movies/detail.html', context)

@require_http_methods(['POST'])
@login_required
def comment_delete(request, movies_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)

    if request.user == comment.user:
        comment.delete()

    return redirect('movies:detail', movies_pk)

@require_http_methods(['POST'])
@login_required
def likes(request, movies_pk):
    movie = Movie.objects.get(pk=movies_pk)

    if request.user in movie.like_user.all():
        movie.like_user.remove(request.user)
    else:
        movie.like_user.add(request.user)

    return redirect('movies:index')

Django/디버깅 시험대비/4-21 디버깅 시험대비/movies/templates/movies/create.html
{% extends "base.html" %}

{% block content %}
<h1>Create</h1>
<form action="{% url "movies:create" %}" method = "POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type ="submit">제출</button>
</form>
{% endblock content %}

Django/디버깅 시험대비/4-21 디버깅 시험대비/movies/templates/movies/detail.html
{% extends "base.html" %}

{% block content %}
<h1>DETAIL PAGE</h1>
<div>
  <p>{{ movie.title }}</p>
  <p>{{ movie.content }}</p>
</div>
<hr>
<div>
  <p><h3>댓글 목록</h3></p>
  <ul>
  {% for comment in comments %}
    <li>
      <p>{{ comment.content }}</p>
      <p>
        작성자 : <a href="{% url "accounts:profile" comment.user.username %}">{{ comment.user.username }}</a>
      </p>
    </li>
  {% empty %}
  </ul>
  <p>아직 댓글이 없네요..</p>
  {% endfor %}
  </ul>
  <hr>
  <form action="{% url "movies:comment_create" movie.pk %}" method='POST'>
    {% csrf_token %}
    {{ comment_form }}
    <input type="submit" value="Submit">
  </form>
  <a href="{% url "movies:update" movie.pk %}">UPDATE</a>
  <form action="{% url "movies:delete" movie.pk %}" method='POST'>
    {% csrf_token %}
    <input type="submit" value="DELETE">
  </form>
  <a href="{% url "movies:index" %}">BACK</a>
</div>



{% endblock content %}

Django/디버깅 시험대비/4-21 디버깅 시험대비/movies/templates/movies/index.html
{% extends "base.html" %}

{% block content %}
<h1>INDEX PAGE</h1>

<div>
  {% for movie in movies %}
    <div>
      <p>{{ movie.title }}</p>
      <a href="{% url "movies:detail" movie.pk %}">DETAIL</a>
      <form action="{% url "movies:likes" movie.pk %}" method='POST'>
        {% csrf_token %}
        {% if request.user in movie.like_user.all %}
          <input type="submit" value="♥">
        {% else %}
          <input type="submit" value="♡">
        {% endif %}
      </form>
    </div>
    <hr>
  {% endfor %}
</div>

{% endblock content %}

Django/디버깅 시험대비/4-21 디버깅 시험대비/movies/templates/movies/update.html
{% extends "base.html" %}

{% block content %}
<h1>Update</h1>
<form action="{% url "movies:update" movie.pk %}" method='POST'>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="제출">
</form>

{% endblock content %}