Django/디버깅 시험대비/4-21 디버깅 시험대비/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('<int:user_pk>/update/', views.update, name='update'),
    path('<int:user_pk>/delete/', views.delete, name='delete'),
    path('<int:user_pk>/password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

Django/디버깅 시험대비/4-21 디버깅 시험대비/movies/urls.py
from django.urls import path
from .import views


app_name = "movies"

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:movies_pk>/', views.detail, name='detail'),
    path('<int:movies_pk>/update/', views.update, name='update'),
    path('<int:movies_pk>/delete/', views.delete, name='delete'),
    path('<int:movies_pk>/comment/', views.comment_create, name='comment_create'),
    path('<int:movies_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:movies_pk>/likes', views.likes, name='likes'),

]

Django/디버깅 시험대비/4-21 디버깅 시험대비/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

Django/디버깅 시험대비/4-21 디버깅 시험대비/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    

Django/디버깅 시험대비/4-21 디버깅 시험대비/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.contrib.auth import models, get_user_model

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(
        label='Email address'
    )
                             
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2',)

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = (
            'email',
            'first_name',
            'last_name',
        )

Django/디버깅 시험대비/4-21 디버깅 시험대비/accounts/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from .forms import CustomUserCreationForm, CustomUserChangeForm
from movies.models import Movie


# Create your views here.
@require_http_methods(['GET', 'POST'])
def login(request):
    if request.method == 'POST':
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            return redirect('movies:index')
    else:
        login_form = AuthenticationForm()
    context = {
        'login_form': login_form,
    }
    return render(request, 'accounts/login.html', context)

# @require_http_methods(['POST'])
@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:index')

@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.method == 'POST':
        signup_form = CustomUserCreationForm(request.POST)
        if signup_form.is_valid():
            user = signup_form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        signup_form = CustomUserCreationForm()
    context = {
        'signup_form': signup_form,
    }
    return render(request, 'accounts/signup.html', context)

@require_http_methods(['GET', 'POST'])
@login_required
def update(request, user_pk):
    if request.method == 'POST':
        user_form = CustomUserChangeForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            return redirect('movies:index')
    else:
        user_form = CustomUserChangeForm(instance=request.user)
    context = {
        'user_form': user_form,
    }
    return render(request, 'accounts/update.html', context)

@require_http_methods(['GET', 'POST'])
@login_required
def change_password(request, user_pk):
    if request.method == 'POST':
        change_pw_form = PasswordChangeForm(request.user, request.POST)
        if change_pw_form.is_valid():
            user = change_pw_form.save()
            update_session_auth_hash(request, user)
            return redirect('movies:index')
    change_pw_form = PasswordChangeForm(request.user)
    context = {
        'change_pw_form': change_pw_form,
    }
    return render(request, 'accounts/change_password.html', context)

@require_http_methods(['POST'])
@login_required
def delete(request, user_pk):
    user = get_user_model()
    person = user.objects.get(pk=user_pk)
    if request.user == person:
        person.delete()
    return redirect('movies:index')

# @require_http_methods(['POST'])
def profile(request, username):
    user = get_user_model()
    person = user.objects.get(username=username)
    movies = Movie.objects.filter(user_id=person.pk)
    like_movies = person.like_movies.all()
    context = {
        'person': person,
        'movies': movies,
        'like_movies': like_movies,
    }
    return render(request, 'accounts/profile.html', context)

@require_http_methods(['POST'])
def follow(request, user_pk):
    user = get_user_model()
    person = user.objects.get(pk=user_pk)
    if person != request.user:
        if request.user in person.followers.all():
            person.followers.remove(request.user)
        else:
            person.followers.add(request.user)
    return redirect('accounts:profile', person.username)

Django/디버깅 시험대비/4-21 디버깅 시험대비/accounts/templates/accounts/change_password.html
{% extends "base.html" %}

{% block content %}
<h1>CHANGE PASSWORD</h1>
<hr>
<form action="{% url "accounts:change_password" user.pk %}" method='POST'>
  {% csrf_token %}
  {{ change_pw_form.as_p }}
  <input type="submit" value="비밀번호 변경">
</form>
{% endblock content %}

Django/디버깅 시험대비/4-21 디버깅 시험대비/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<h1>LOGIN PAGE</h1>
<hr>
<form action="{% url "accounts:login" %}" method='POST'>
  {% csrf_token %}
  {{ login_form.as_p }}
  <input type="submit" value="로그인">
</form>
{% endblock content %}

Django/디버깅 시험대비/4-21 디버깅 시험대비/accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}
<h1>{{ person.username }}님의 프로필</h1>
<hr>
<p>팔로워 : {{ person.followers.all|length }}</p>
<p>팔로잉 : {{ person.followings.all|length }}</p>
{% if request.user != person %}
<form action="{% url "accounts:follow" person.pk %}" method='POST'>
  {% csrf_token %}
  {% if request.user in person.followers.all %}
    <input type="submit" value="언팔로우">
  {% else %}
    <input type="submit" value="팔로우">
  {% endif %}
  </form>
{% endif %}
<hr>
<h3>작성한 영화 목록</h3>
<ul>
{% for movie in movies %}
  <li>
    <a href="{% url "movies:detail" movie.pk %}">{{ movie.title }}</a>
  </li>  
{% empty %}
</ul>
<p>아직 작성한 영화가 없습니다.</p>
{% endfor %}
</ul>
<hr>
<h3>좋아요 누른 영화 목록</h3>
<ul>
{% for movie in like_movies %}
<li>
  <a href="{% url "movies:detail" movie.pk %}">{{ movie.title }}</a>
</li>  
{% empty %}
</ul>
  <p>아직 좋아요를 누른 영화가 없습니다.</p>
{% endfor %}
</ul>
{% endblock content %}

Django/디버깅 시험대비/4-21 디버깅 시험대비/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
<h1>SIGNUP PAGE</h1>
<hr>
<form action="{% url "accounts:signup" %}" method='POST'>
  {% csrf_token %}
  {{ signup_form.as_p }}
  <input type="submit" value="회원가입">
</form>
{% endblock content %}

Django/디버깅 시험대비/4-21 디버깅 시험대비/accounts/templates/accounts/update.html
{% extends "base.html" %}

{% block content %}
<h1>USER INFO UPDATE PAGE</h1>
<hr>
<form action="{% url "accounts:update" user.pk %}" method='POST'>
  {% csrf_token %}
  {{ user_form.as_p }}
  <input type="submit" value="수정">
</form>
<form action="{% url "accounts:delete" user.pk %}" method='POST'>
  {% csrf_token %}
  <input type="submit" value="회원탈퇴">
</form>
{% endblock content %}